// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MoneyInfo:MonoBehaviour
{
    public TextAsset csv;

    void Start()
    { Load(csv); }

	public class Row
	{
		public string piggys;
		public string cost;
		public string taste;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.piggys = grid[i][0];
			row.cost = grid[i][1];
			row.taste = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_piggys(string find)
	{
		return rowList.Find(x => x.piggys == find);
	}
	public List<Row> FindAll_piggys(string find)
	{
		return rowList.FindAll(x => x.piggys == find);
	}
	public Row Find_cost(string find)
	{
		return rowList.Find(x => x.cost == find);
	}
	public List<Row> FindAll_cost(string find)
	{
		return rowList.FindAll(x => x.cost == find);
	}
	public Row Find_taste(string find)
	{
		return rowList.Find(x => x.taste == find);
	}
	public List<Row> FindAll_taste(string find)
	{
		return rowList.FindAll(x => x.taste == find);
	}

}